// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvUkAUyCmcfewrofoMDTZv2sCB5FOQa4c',
    appId: '1:329926243871:web:ac02ad617917238305872a',
    messagingSenderId: '329926243871',
    projectId: 'hackathon-2024-f7523',
    authDomain: 'hackathon-2024-f7523.firebaseapp.com',
    storageBucket: 'hackathon-2024-f7523.appspot.com',
    measurementId: 'G-T2D0Y4302V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0J5PAFU2abchhupjiFPz3Nfz8upuOFtI',
    appId: '1:329926243871:android:14fb9cc4a965295905872a',
    messagingSenderId: '329926243871',
    projectId: 'hackathon-2024-f7523',
    storageBucket: 'hackathon-2024-f7523.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb_AqV32uOntjItlBqEGp9XSULzfR_71Y',
    appId: '1:329926243871:ios:d45bbd3c0247de2205872a',
    messagingSenderId: '329926243871',
    projectId: 'hackathon-2024-f7523',
    storageBucket: 'hackathon-2024-f7523.appspot.com',
    iosBundleId: 'com.example.hackathon2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb_AqV32uOntjItlBqEGp9XSULzfR_71Y',
    appId: '1:329926243871:ios:0f3d6b11c0a2c00805872a',
    messagingSenderId: '329926243871',
    projectId: 'hackathon-2024-f7523',
    storageBucket: 'hackathon-2024-f7523.appspot.com',
    iosBundleId: 'com.example.hackathon2024.RunnerTests',
  );
}
